name: ai_chat_app
description: A multimodal AI chat application with impressive UI.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Architecture & state management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.0
  injectable: ^2.1.2
  
  # UI components
  flutter_svg: ^2.0.7
  google_fonts: ^5.1.0
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  lottie: ^2.6.0
  flutter_markdown: ^0.6.18
  photo_view: ^0.14.0
  
  # Navigation
  auto_route: ^7.8.0
  
  # Data handling
  dio: ^5.3.2
  shared_preferences: ^2.2.0
  hive: ^2.2.3
  path_provider: ^2.1.0
  internet_connection_checker: ^1.0.0
  dartz: ^0.10.1
  
  # Media handling
  file_picker: ^5.5.0
  image_picker: ^1.0.4
  video_player: ^2.7.0
  audioplayers: ^5.2.0
  flutter_pdfview: ^1.3.1
  flutter_highlight: ^0.7.0
  
  # Accessibility
  flutter_tts: ^3.8.3
  speech_to_text: ^6.3.0
  
  # Analytics & performance
  firebase_core: ^2.15.1
  firebase_analytics: ^10.4.5
  firebase_crashlytics: ^3.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  build_runner: ^2.4.15
  auto_route_generator: ^7.3.1
  injectable_generator: ^2.6.2
  bloc_test: ^9.1.4
  
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/fonts/